export default function Dummy(props) {
    return null;
}

export const getServerSideProps = async (context) => {
    const { res, query } = context;
    let subdomain = context.req.headers.host.split('.')[0];
    if (subdomain === 'localhost:3000' || subdomain === 'thenewzkit' || subdomain === 'www'){
        subdomain = "home";
    }
    res.setHeader("Content-Type", "text/txt");
    res.write(`robots.txt generated by www.seoptimer.com\nUser-agent: *\nDisallow:\nDisallow: /cgi-bin/\nSitemap: http://${subdomain === 'home'? 'www': subdomain}.thenewzkit.com/sitemap.xml`);
    res.end();

    return {
        props: {},
    };
}